### PR TITLE
Update code and project for Swift 4

### PR DESCRIPTION
**Pull request by ejmartin504**
Using xCode 9 beta 3. 
Was not able to run the tests for some reason, so they are not updated unfortunately. Something to do with the simulators on my machine.

### CODE REVIEW

**Comment by ejmartin504** [comment]
This is pretty basic and just ports over everything as straightforwardly as possible, using the new NSAttributedStringKey API.

The new API is so convenient, it _almost_ makes this library no longer necessary! But the wrapper around the existing API is still nice :-)

**Comment by muukii** [comment]
@ejmartin504 
Hi, I think this PR looks good for me.
Thanks!

@delba 
Could you merge and release?

**Comment by efremidze** [comment]
We should merge this soon

**Comment by txaiwieser** [comment]
Any info on this one?

**Comment by ejmartin504** [comment]
I haven't looked at this in a while, but it's worth pointing out that this PR does change the public facing API, since it changes the type of 
```swift 
open fileprivate(set) var dictionary: [String: Any] = [:]
```
to:
 ```swift
open fileprivate(set) var dictionary: [NSAttributedStringKey: Any] = [:]
```

**Comment by muukii** [comment]
I think these properties should be as follows.

```swift
open fileprivate(set) var rawDictionary: [String: Any]
open fileprivate(set) var dictionary: [NSAttributedStringKey: Any]
```

**Comment by ejmartin504** [comment]
@muukii that makes sense to me. It's still a breaking change to the API, but I think it is a better solution than keeping `dictionary` as `[String: Any]`

**Comment by ejmartin504** [comment]
This library doesn't seem to be maintained. Closing.

**Pull request closed without merging**
